// Code generated by "stringer -type=ContactType -output=contact_type_string.go"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Webitel-0]
	_ = x[User-1]
	_ = x[Bot-2]
}

const _ContactType_name = "WebitelUserBot"

var _ContactType_index = [...]uint8{0, 7, 11, 14}

func (i ContactType) String() string {
	if i < 0 || i >= ContactType(len(_ContactType_index)-1) {
		return "ContactType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ContactType_name[_ContactType_index[i]:_ContactType_index[i+1]]
}
